apiVersion: v1
kind: Service
metadata:
  name: ethereal-backend-svc
  namespace: sunday-app
spec:
  type: NodePort 
  selector:
    app: ethereal-backend
  ports:
    - port: 8080    
      targetPort: 3000 
      nodePort: 30001
---
